### ISSUE TITLE
How  to use jenkins crediential plugin api

### ISSUE THREAD

**Issue by wulonghui** [arangamani/jenkins_api_client#162]
Does jenkins crediential plugin support restapi , how to create credientials by ruby client?
Any example?

**Comment by WuLonghui** [comment]
@arangamani Thanks in advance

**Comment by dachary** [comment]
I'm also looking for a way to create a new credential via the REST API (or even the cli). It looks like it should be somewhere in https://github.com/jenkinsci/credentials-plugin/ but I'm not familiar enough with jenkins to figure it out.

**Comment by goindwalia** [comment]
I am looking for the same @dachary , let me know if you have figured out this.

**Comment by rG8KDQ5YXlJ7fcE80CLmNx** [comment]
@wulonghui Hitting an endpoint that actually exists may help.
Try: ```"/credentials/configSubmit"``` instead of ```"/credentials/configSumbit"```
I've tested on Jenkins 1.619 and it works fine.

**Comment by wulonghui** [comment]
@rG8KDQ5YXlJ7fcE80CLmNx Thanks

**Comment by luisfernandos** [comment]
Try this:

 curl -X POST 'http://<user>:<token>@<jenkins_server>:8080/credentials/store/system/domain/_/createCredentials' \
 --data-urlencode 'json={
 "": "0",
 "credentials": {
 "scope": "GLOBAL",
 "id": "identification",
 "username": "manu",
 "password": "bar",
 "description": "linda",
 "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
 }
 }'

**Comment by jurgenweber** [comment]
I am having the same issue but just trying to do it bash, it will not accept my privateKey value.

Caused: java.lang.IllegalArgumentException: Failed to convert the privateKeySource parameter of the constructor public com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey(com.cloudbees.plugins.credentials.CredentialsScope,java.lang.String,java.lang.String,com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$PrivateKeySource,java.lang.String,java.lang.String) any ideas?

**Comment by gogskrish** [comment]
There is a problem with SSH private_key direct posting. when i post it with ssh private key, it is removing "+" sign from the content. Am using ansible for this.

- name: configure ssh credential
  uri:
    url: "https://{{ host_ip }}/credentials/store/system/domain/_/createCredentials"
    method: POST
    headers:
       Content-Type: "application/x-www-form-urlencoded"
       Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
       Accept-Encoding: "gzip, deflate, br"
    others: "--data-urlencode"
    body: 'json={"": "6", 
           "credentials": {
                "scope": "GLOBAL",
                "username": "{{ ssh_cred.value.username }}",
                "privateKeySource": {
                     "value": "0",
                     "privateKey": "-----BEGIN RSA PRIVATE KEY-----
                                           /abbhsshsnne +bbbebe
                                           ----END RSA PRIVATE KEY-----",
                     "stapler-class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource"
                     },
                     "passphrase": "{{ ssh_cred.value.passphrase }}",
                     "id": "{{ ssh_cred.value.id }}",
                     "description": "{{ ssh_cred.value.description }}",
                     "stapler-class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey",
                     "$class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"
               }
             }'
    validate_certs: no
    follow_redirects: yes
    register: login
    return_content: yes
  with_dict: "{{ ssh_credentials }}"
  loop_control:
    loop_var: ssh_cred

This is removing + sign which in the private key. also it you take the key from any variable, it is adding 'u[ private key]'
am i doing anything wrong.

**Comment by sergeypapyan** [comment]
@gogskrish You should urlencode the key contents
