### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by dylanmckay** [arangamani/jenkins_api_client#208]
Would you be able to bump the Ruby gem version so the SOCKS proxy stuff can be used :)

**Comment by dylanmckay** [comment]
Pinging

**Comment by dylanmckay** [comment]
Ping

**Comment by arangamani** [comment]
Version 1.4.3 is pushed with support for SOCKS proxies. Thank you very much for your contribution. I sincerely apologize for my delay.

**Comment by dylanmckay** [comment]
No problem! Thanks :)
