### ISSUE TITLE
Is there a reason for the version pin to json 1.0?

### ISSUE THREAD

**Issue by craigske** [arangamani/jenkins_api_client#220]
https://github.com/arangamani/jenkins_api_client/blob/master/Gemfile#L8

Causes a lot of compatibility issues.

**Comment by arangamani** [comment]
It was just for Ruby 1.9 compatibility. We can remove support for ruby 1.9 and bump the major version. Send a PR if you're interested and I'll be glad to merge and ship a new version.

**Comment by sjernigan** [comment]
I see at least 3 forks to resolve this.  I hate to see this good gem fragment, perhaps you can merge one back in.  Thanks for your effort.

**Comment by arangamani** [comment]
@sjernigan I'll try to look into it tonight.

**Comment by ninp0** [comment]
any progress on this item?
