### ISSUE TITLE
Hello, I am interested in contributing with this work through a Spanish translation, which is my native language.

### ISSUE THREAD

**Issue by LuigiBaute** [arangamani/jenkins_api_client#268]

**Comment by katelovescode** [comment]
That would be great!  Please submit a pull request when  you're finished!

**Comment by LuigiBaute** [comment]
https://github.com/LuigiBaute/LuigiBaute-jenkins_api_client_Doc_ES

**Comment by LuigiBaute** [comment]
Hi, have you checked the pull request? I'd love to get an answer, thanks.

**Comment by LuigiBaute** [comment]
????

**Comment by katelovescode** [comment]
Hi @LuigiBaute - we're in the middle of working through a Release Candidate and have some other PRs to attend to.  We'll look at this as soon as we get a chance.
