### ISSUE TITLE
gem 'jenkins_api_client', '~> 1.4', '>= 1.4.2'

### ISSUE THREAD

**Issue by EricDier** [arangamani/jenkins_api_client#281]

**Comment by EricDier** [comment]
what is gem 'jenkins_api_client', '~> 1.4', '>= 1.4.2'

**Comment by luke-hill** [comment]
This means any version from 1.4 - 1.100000000 but it must be bigger than 1.4.2

This isn't really an issue so could you close it.

See semver.org for more info.
