### ISSUE TITLE
Use tree parameter for obtaining portion of JSON to improve performance

### ISSUE THREAD

**Issue by arangamani** [arangamani/jenkins_api_client#89]
The current implementation gets the whole JSON and it will degrade the performance if the number of jobs is high. Research and implement use the usage of tree parameter in get requests wherever possible.

**Comment by stjohnjohnson** [comment]
I'm affected by this as well, I have Jenkins farms with 10s of thousands of jobs each.  I've provided a PR to fix the three areas I could find that were loading `{root}/api/json`

**Comment by katelovescode** [comment]
Fixed with #179
